import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // might need to add overflow-auto to the div to make this scrollable
    <html lang="en">
      <body className="h-screen flex flex-col overflow-hidden">
        <Navbar />
          <div className="flex flex-1 flex-col bg-[#253f4b]">{children}</div> 
      </body>
    </html>
  );
}
