export const createShipwreckFields = [
  { name: 'ship_name', placeholder: 'Ship Name', type: 'text' },
  { name: 'aka', placeholder: 'AKA', type: 'text' },
  { name: 'owner', placeholder: 'Owner', type: 'text' },
  { name: 'vessel_type', placeholder: 'Vessel Type', type: 'text' },
  { name: 'year_built', placeholder: 'Year Built', type: 'number' },
  { name: 'build_location', placeholder: 'Build Location', type: 'text' },
  { name: 'date_lost', placeholder: 'Date Lost', type: 'text' },
  { name: 'year_lost', placeholder: 'Year Lost', type: 'number' },
  { name: 'month_lost', placeholder: 'Month Lost', type: 'number' },
  { name: 'day_lost', placeholder: 'Day Lost', type: 'number' },
  { name: 'location_lost', placeholder: 'Location Lost', type: 'text' },
  { name: 'latitude_lost', placeholder: 'Latitude Lost', type: 'number' },
  { name: 'longitude_lost', placeholder: 'Longitude Lost', type: 'number' },
  { name: 'cause_of_loss', placeholder: 'Cause of Loss', type: 'text' },
  { name: 'construction', placeholder: 'Construction', type: 'text' },
  { name: 'flag', placeholder: 'Flag', type: 'text' },
  { name: 'length', placeholder: 'Length', type: 'number' },
  { name: 'beam', placeholder: 'Beam', type: 'number' },
  { name: 'draft', placeholder: 'Draft', type: 'number' },
  { name: 'gross_tonnage', placeholder: 'Gross Tonnage', type: 'number' },
  { name: 'net_tonnage', placeholder: 'Net Tonnage', type: 'number' },
  { name: 'home_port', placeholder: 'Home Port', type: 'text' },
  { name: 'departure_port', placeholder: 'Departure Port', type: 'text' },
  { name: 'destination_port', placeholder: 'Destination Port', type: 'text' },
  { name: 'master', placeholder: 'Master', type: 'text' },
  { name: 'num_crew', placeholder: 'Number of Crew', type: 'number' },
  { name: 'num_pass', placeholder: 'Number of Passengers', type: 'number' },
  { name: 'lives_lost', placeholder: 'Lives Lost', type: 'number' },
  { name: 'ship_value', placeholder: 'Ship Value', type: 'number' },
  { name: 'cargo_value', placeholder: 'Cargo Value', type: 'number' },
  { name: 'nature_of_cargo', placeholder: 'Nature of Cargo', type: 'text' },
  { name: 'uslss_station_name', placeholder: 'USLSS Station Name', type: 'text' },
];

export const dashboardFields = [
  { key: 'aka', label: 'AKA' },
  { key: 'owner', label: 'Owner' },
  { key: 'vessel_type', label: 'Vessel Type' },
  { key: 'year_built', label: 'Year Built' },
  { key: 'build_location', label: 'Build Location' },
  { key: 'date_lost', label: 'Date Lost' },
  { key: 'year_lost', label: 'Year Lost' },
  { key: 'month_lost', label: 'Month Lost' },
  { key: 'day_lost', label: 'Day Lost' },
  { key: 'location_lost', label: 'Location Lost' },
  { key: 'latitude_lost', label: 'Latitude Lost' },
  { key: 'longitude_lost', label: 'Longitude Lost' },
  { key: 'cause_of_loss', label: 'Cause of Loss' },
  { key: 'construction', label: 'Construction' },
  { key: 'flag', label: 'Flag' },
  { key: 'length', label: 'Length' },
  { key: 'beam', label: 'Beam' },
  { key: 'draft', label: 'Draft' },
  { key: 'gross_tonnage', label: 'Gross Tonnage' },
  { key: 'net_tonnage', label: 'Net Tonnage' },
  { key: 'home_port', label: 'Home Port' },
  { key: 'departure_port', label: 'Departure Port' },
  { key: 'destination_port', label: 'Destination Port' },
  { key: 'master', label: 'Master' },
  { key: 'num_crew', label: 'Number of Crew' },
  { key: 'num_pass', label: 'Number of Passengers' },
  { key: 'lives_lost', label: 'Lives Lost' },
  { key: 'ship_value', label: 'Ship Value' },
  { key: 'cargo_value', label: 'Cargo Value' },
  { key: 'nature_of_cargo', label: 'Nature of Cargo' },
  { key: 'uslss_station_name', label: 'USLSS Station Name' },
];

export const sortByFields = [
  { value: 'ship_name', label: 'Sort By Name'},
  { value: 'year_built', label: 'Sort By Year Built'},
  { value: 'year_lost', label: 'Sort By Year Lost'},
  { value: 'location_lost', label: 'Sort By Location Lost'},
  { value: 'home_port', label: 'Sort By Home Port'},
];

export const filterFields = [
  { name: 'ship_name', placeholder: 'Ship Name', label: 'Name', type: 'text' },
  { name: 'year_built_range_start', placeholder: 'Year Built', label: 'Year Built Range Start', type: 'number' },
  { name: 'year_built_range_end', placeholder: 'Year Built', label: 'Year Built Range End', type: 'number' },
];